alexeymezenin/laravel-best-practices

- README.md
I found 2 lines of text written in Russian. I translated it into English with some help of my good friend Google Translate. :)
> Translation of Russian text

- README.md
I found your suggestions incredible, so I thought it would be nice if they were written in Portuguese. Please accept them in your listing.
In addition, I adjusted the list of translations, for better visualization.
> Add link for version in pr-br

- README.md
https://laravel.com/docs/5.6/blade#displaying-data
> Best use of json in blade templates

- french.md
Hi,
Here is the translation of **REAME.md** in **French**.
> French translate.

- japanese.md
Hi,
Here is the translation of REAME.md in Japanese.
> Japanese translate

- chinese.md
hello，here is  a chinese translation.
哈咯，我们创建了一个中文的翻译文本
> Create chinese translation

- thai.md
I have translated this article into Thai. Please check and add to your document.
Thank You.
Kongvut
> Translate to Thai language.

- README.md
- chinese.md
- french.md
- german.md
- italian.md
- japanese.md
- persian.md
- thai.md
- turkish.md
Hello, Merge my PR I was added two transalation file in german and italian language
> Translate to German and Italian language.

- french.md
Small syntax correction of the French translation.
> Some french syntax

- french.md
I did a few corrections in french.md.
> Corrections in french.md

- README.md
@alexeymezenin  **Thank you for such an initiative.**
> Added link to the Azerbaijani translation

- italian.md
I fixed some incorrect translations.
> fix: Improved Italian translation

- README.md
- arabic.md
- bangla.md
- chinese.md
- french.md
- german.md
- indonesia.md
- italian.md
- japanese.md
- persian.md
- polish.md
- russian.md
- spanish.md
- thai.md
- traditional-chinese.md
- turkish.md
- ukrainian.md
> docs: Add new development environment Laravel Sail

- README.md
Simple update to README. Reasoning is as follows:  
1. The "IoC (Inversion of Control) Container" term (from [Laravel 4.2](https://laravel.com/docs/4.2/ioc)) has been deprecated in favor of "Service Container" (current [Laravel 9.x](https://laravel.com/docs/9.x/container#:~:text=The%20Laravel%20service%20container%20is,cases%2C%20%22setter%22%20methods.)). Rather than replace it entirely, I've added Service Container for clarity.  
2. This section demos dependency injection (i.e. the IoC part) but does not demo how Facades can be better used than classes. I'm pretty new to Laravel so not sure what a good example of the Facade strategy would be, but one should either be added or we should omit the Facade suggestion from this section's header. I've opted to do the latter for now and start …
> Clarify "Use IoC container or facades instead of new Class" best practice section of README

- README.md
- arabic.md
- bangla.md
- chinese.md
- french.md
- german.md
- indonesia.md
- italian.md
- japanese.md
- persian.md
- polish.md
- russian.md
- spanish.md
- thai.md
- traditional-chinese.md
- turkish.md
- ukrainian.md
- urdu.md
Pest is a Testing Framework with a focus on simplicity. It was carefully crafted to bring the joy of testing to Laravel PHP.
Pest website: https://pestphp.com
> Add Pest to Unit testing tool

- german.md
Hey everyone,
I'm suggesting the following tweaks for the German translation. If anyone feels there should be adjust please comment.
Peter
> Tweak Wording in German translation

- README.md
- arabic.md
- bangla.md
- chinese.md
- french.md
- german.md
- indonesia.md
- italian.md
- japanese.md
- persian.md
- russian.md
- spanish.md
- thai.md
- traditional-chinese.md
- turkish.md
- ukrainian.md
- urdu.md
Solves #124 
I completely removed the return type specification to match the other files.
> Fix wrong return type (solves #124)

- README.md
> Fix tool name

- README.md
- arabic.md
- bangla.md
- chinese.md
- french.md
- german.md
- indonesia.md
- italian.md
- japanese.md
- persian.md
- polish.md
- russian.md
- spanish.md
- thai.md
- traditional-chinese.md
- turkish.md
- ukrainian.md
- urdu.md
The `$dates` property is deprecated, use `$casts` instead
> `$dates` property is deprecated, use `$casts` instead

- french.md
Fixed broken links on French MD file.
> fix: links on french doc

- README.md
- turkmen.md
Translated the "Laravel Best Practices" information into Turkmen language. Ensured that the translation preserves the original meaning and maintains clarity for Turkmen-speaking developers.
> Turkmen language
